version: "3.8"

services:
  airflow-worker:
    build: .
    container_name: airflow-worker
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW_HOME=/opt/airflow

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./app/backend/models:/opt/airflow/model_output

    command: ["sh", "-c", "airflow webserver -p 8080 & airflow scheduler"]
